### ISSUE TITLE
UX UI

### ISSUE THREAD

**Issue by U1320100568** [U1320100568/Just_Get_Ready_For_Learn_Learn_Learn...#2]
# Sketch 
# Zeplin

**Comment by U1320100568** [comment]
# Scss
[前端純CSS切版體會+技巧雜筆](https://noootown.wordpress.com/2016/01/29/css-scss-tips/)
[使用scss來加速寫css吧!](http://blog.visioncan.com/2011/sass-scss-your-css/)
[scss文章](https://blog.user.today/scss/)

**Comment by U1320100568** [comment]
# Scroll bar
[把scrolbar 消失](https://stackoverflow.com/a/16671476)
[改變樣式](https://noootown.wordpress.com/2016/01/23/css-custom-scrollbar/)
  margin 稍微改一下

**Comment by U1320100568** [comment]
background
https://gratisography.com/

[Perfect Full Page Background](https://css-tricks.com/perfect-full-page-background-image/)
`background: url(asset/bg.jpg) no-repeat center center fixed;
			background-size: cover;`

**Comment by U1320100568** [comment]
# Checkbox & Radio
```css
input[type="checkbox"]{
    margin-right: 10px;
    vertical-align: middle;
    -webkit-appearance: none;
    border: 1px solid #cacece;
    padding : 9px;
    border-radius:4px;
    display:inline-block;
    position:relative;
    outline:none;
}

input[type="checkbox"]:checked:after{
  content: '\2713';
  font-size:18px;
  position:absolute;
  top:-5px;
  left:2px;
  color:#000000;
}

input[type="radio"]{
  margin-right: 10px;
    vertical-align: middle;
    -webkit-appearance: none;
    border: 1px solid #cacece;
    padding : 9px;
    border-radius:50px;
    display:inline-block;
    position:relative;
    outline:none;
}

input[type="radio"]:checked:after{
  content: '';
  width:12px;
  height:12px;
  border-radius:50px;
  font-size:18px;
  position:absolute;
  top:3px;
  left:3px;
  color:#000000;
  background-color:#99a1a7;
  text-shadow:0px;
  font-size:32px; 
}
```
